language: php
php:
  - '5.5'
  - '5.6'
services:
  - mysql
install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install
before_script:
  - mysql -e 'create database desconecta_test;'

script: php vendor/codeception/codeception/codecept run